scrolling {
    column_width = 0.75
    fullscreen_on_one_column = false
    explicit_column_widths = 0.25, 0.5, 0.75, 1.0
    focus_fit_method = 1
    follow_min_visible = 0.25
}

bind = $mainMod, L, layoutmsg, focus r
bind = $mainMod, H, layoutmsg, focus l
bind = $mainMod, K, layoutmsg, focus u
bind = $mainMod, J, layoutmsg, focus d
bind = $mainMod CTRL, L, layoutmsg, swapcol r
bind = $mainMod CTRL, H, layoutmsg, swapcol l
bind = $mainMod, Home, layoutmsg, fit tobeg
bind = $mainMod, End, layoutmsg, fit toend
bind = $mainMod, Equal, layoutmsg, colresize +conf
bind = $mainMod, Minus, layoutmsg, colresize -conf
bind = $mainMod, Comma, layoutmsg, move -col
bind = $mainMod, Period, layoutmsg, move +col
bind = $mainMod, Slash, layoutmsg, promote
bind = $mainMod, C, layoutmsg, togglefit

# bind = $mainMod, S, layoutmsg, fit all
bind = $mainMod, D, layoutmsg, fit visible
bind = $mainMod SHIFT, L, exec, hyprctl dispatch movewindow r
bind = $mainMod SHIFT, H, exec, hyprctl dispatch movewindow l
bind = $mainMod ALT, L, exec, hyprctl dispatch moveintoorcreategroup r
bind = $mainMod ALT, H, exec, hyprctl dispatch moveintoorcreategroup l
bind = $mainMod ALT, K, exec, hyprctl dispatch moveintoorcreategroup u
bind = $mainMod ALT, J, exec, hyprctl dispatch moveintoorcreategroup d
bind = $mainMod SHIFT ALT, L, exec, hyprctl dispatch moveoutofgroup r
bind = $mainMod SHIFT ALT, H, exec, hyprctl dispatch moveoutofgroup l
bind = $mainMod SHIFT ALT, K, exec, hyprctl dispatch moveoutofgroup u
bind = $mainMod SHIFT ALT, J, exec, hyprctl dispatch moveoutofgroup d
bind = $mainMod SHIFT, K, exec, hyprctl dispatch movewindow u
bind = $mainMod SHIFT, J, exec, hyprctl dispatch movewindow d
