bind = $mainMod, Grave, hyprtasking:toggle, all
bind = $mainMod, I, hyprtasking:toggle, cursor

# bind = $mainMod, h, hyprtasking:move, left
# bind = $mainMod, j, hyprtasking:move, down
# bind = $mainMod, k, hyprtasking:move, up
# bind = $mainMod, l, hyprtasking:move, right

plugin {
    hyprtasking {
        rows = 3
        exit_behavior = interacted original hovered 
        gap_size = 3
        bg_color = $surface1
    }
}
