bind = SUPER, grave, hyprtasking:toggle, cursor
bind = SUPER, space, hyprtasking:toggle, all
bind = , escape, hyprtasking:if_active, hyprtasking:toggle cursor

# bind = SUPER, X, hyprtasking:killhovered

# bind = SUPER, left, hyprtasking:move, left
# bind = SUPER, down, hyprtasking:move, down
# bind = SUPER, up, hyprtasking:move, up
# bind = SUPER, right, hyprtasking:move, right

plugin {
    hyprtasking {
        layout = grid

        bg_color = 0xff26233a
        gap_size = 20
        border_size = 3
        exit_on_hovered = false

        gestures {
            enabled = true
            move_fingers = 3
            move_distance = 300
            open_fingers = 4
            open_distance = 300
            open_positive = true
        }

        grid {
            rows = 3
            cols = 1
            loop = false
            gaps_use_aspect_ration = true
        }

        linear {
            height = 300
            scroll_speed = 1
            blur = false
        }
    }
}
