bind = SUPER, grave, hyprtasking:toggle, cursor
bind = SUPER, space, hyprtasking:toggle, all

bind = SUPER, X, hyprtasking:killhovered

# bind = SUPER, H, hyprtasking:move, left
# bind = SUPER, J, hyprtasking:move, down
# bind = SUPER, K, hyprtasking:move, up
# bind = SUPER, L, hyprtasking:move, right

plugin {
    hyprtasking {
        layout = linear

        bg_color = 0xff26233a
        gap_size = 20
        border_size = 2
        exit_behavior = active interacted original hovered

        grid {
            rows = 3
            cols = 3
        }
        linear {
            height = 300
            scroll_speed = 1.1
            blur = 0
        }
    }
}
