#!/bin/bash

## Files
# CONFIG="$HOME/.config/hypr/wofi/config"
# STYLE="$HOME/.config/hypr/wofi/style.css"
# COLORS="$HOME/.config/hypr/wofi/colors"

## Wofi Command
wofi_command="rofi -dmenu -format d \
      --width=350 --height=380 \
      --cache-file=/dev/null \
      --hide-scroll --no-actions"

notification() {
	notify-send "Be Menu" "$1"
}

menu() {
	printf " 1. Dictionary\n"
	printf " 2. Search Man Pages\n"
	printf " 3. Google Search\n"
	printf " 4. Open Git Repository\n"
	printf " 5. Terminal\n"
	printf " 6. Run...\n"
	printf " 7. Kill Process\n"
	printf " 8. Focus Mode\n"
	printf " 9. Wifi Connect\n"
	printf "10. Exit System\n"
}

main() {
	choice=$(menu | ${wofi_command})
	bemenu_input $choice
}

main
