#!/bin/bash

## Files
# CONFIG="$HOME/.config/hypr/wofi/config"
# STYLE="$HOME/.config/hypr/wofi/style.css"
# COLORS="$HOME/.config/hypr/wofi/colors"

## Wofi Command
wofi_command="rofi -dmenu -format d \
      --width=350 --height=380 \
      --cache-file=/dev/null \
      --hide-scroll --no-actions"

notification() {
	notify-send "Be Menu" "$1"
}

menu() {
	printf " 1. Dictionary\n"
	printf " 2. Search Man Pages\n"
	printf " 3. Google Search\n"
	printf " 4. Open Git Repository\n"
	printf " 5. Terminal\n"
	printf " 6. Run...\n"
	printf " 7. Kill Process\n"
	printf " 8. Focus Mode\n"
	printf " 9. Wifi Connect\n"
	printf "10. Exit System\n"
}

main() {
	choice=$(menu | ${wofi_command})

	case $choice in
	1)
		notification "Search dictionary"
		bemenu_input 1
		return
		;;
	2)
		notification "Search man pages"
		bemenu_input 2
		return
		;;
	3)
		notification "Google search"
		bemenu_input 3
		return
		;;
	4)
		notification "Open git repo"
		bemenu_input 4
		return
		;;
	5)
		notification "Open terminal"
		bemenu_input 5
		return
		;;
	6)
		notification "Run..."
		bemenu_input 6
		return
		;;
	7)
		notification "Kill process"
		bemenu_input 7
		return
		;;
	8)
		notification "Focus mode"
		bemenu_input 8
		return
		;;
	9)
		notification "Connect to wifi"
		bemenu_input 9
		return
		;;
	10)
		notification "Exit system"
		bemenu_input 10
		return
		;;
	esac
}

main
