#!/bin/bash

## Files
# CONFIG="$HOME/.config/hypr/wofi/config"
# STYLE="$HOME/.config/hypr/wofi/style.css"
# COLORS="$HOME/.config/hypr/wofi/colors"

## Wofi Command
wofi_command="rofi -dmenu \
      --width=350 --height=380 \
      --cache-file=/dev/null \
      --hide-scroll --no-actions \
      --define=matching=fuzzy"

notification() {
  notify-send "Be Menu" "$1"
}

menu() {
  printf "d. Dictionary\n"
  printf "m. Search Man Pages\n"
  printf "g. Google Search\n"
  printf "r. Open Git Repository\n"
  printf "f. Terminal\n"
  printf "l. Run...\n"
  printf "k. Kill Process\n"
  printf "t. Focus Mode\n"
  printf "w. Wifi Connect\n"
  printf "e. Exit System\n"
}

main() {
  choice=$(menu | ${wofi_command} | cut -d. -f1)

  case $choice in
  d)
    notification "Search dictionary"
    bemenu_input -d
    return
    ;;
  m)
    notification "Search man pages"
    bemenu_input -m
    return
    ;;
  g)
    notification "Google search"
    bemenu_input -g
    return
    ;;
  r)
    notification "Open git repo"
    bemenu_input -r
    return
    ;;
  f)
    notification "Open terminal"
    bemenu_input -f
    return
    ;;
  l)
    notification "Run..."
    bemenu_input -l
    return
    ;;
  k)
    notification "Kill process"
    bemenu_input -k
    return
    ;;
  t)
    notification "Focus mode"
    bemenu_input -t
    return
    ;;
  w)
    notification "Connect to wifi"
    bemenu_input -w
    return
    ;;
  e)
    notification "Kill process"
    bemenu_input -e
    return
    ;;
  esac
}

main
