#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts
DIR=$HOME/.config/hypr/bg
PICS=($(ls ${DIR}))

if [ $# -eq 1 ]; then
  RANDOMPICS=$1
else
  RANDOMPICS=${PICS[$RANDOM % ${#PICS[@]}]}
fi

hyprctl hyprpaper preload "${DIR}/${RANDOMPICS}"
hyprctl hyprpaper wallpaper ",${DIR}/${RANDOMPICS}"
notify-send -i ${DIR}/${RANDOMPICS} "Wallpaper Changed" ${RANDOMPICS}
hyprctl hyprpaper unload unused

$SCRIPTSDIR/generateLockscreenWallpaper.sh "${DIR}/${RANDOMPICS}"
