#!/bin/sh
# sensors | awk '/Package/ {sub(/^\+/, "", $4); sub(/\.0/, "", $4);print $4}'
temp_value=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon6/temp1_input)
temp_celsius=$(echo "scale=1; $temp_value / 1000" | bc)
echo "${temp_celsius}"
