#!/bin/sh
# sensors | awk '/Package/ {sub(/^\+/, "", $4); sub(/\.0/, "", $4);print $4}'
temp_value=$(cat /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon5/temp1_input)
temp_celsius=$(echo "scale=1; $temp_value / 1000" | bc)
echo "${temp_celsius}"
