#!/usr/bin/env bash

scriptsDir="$HOME/.config/hypr/scripts"
rofi_command="vicinae dmenu"

menu() {
  printf "1. Screen\n"
  printf "2. Window\n"
  printf "3. Area\n"
  printf "4. All screens\n"
}

main() {
  choice=$(menu | ${rofi_command} | cut -d. -f1)

  case $choice in
  1)
    sleep 0.5
    dms screenshot full -f jpg -q 85 --stdout | satty -f -
    return
    ;;
  2)
    sleep 0.5
    dms screenshot window -f jpg -q 85 --stdout | satty -f -
    return
    ;;
  3)
    sleep 0.5
    dms screenshot region -f jpg -q 85 --stdout | satty -f -
    return
    ;;
  4)
    sleep 0.5
    dms screenshot all -f jpg -q 85 --stdout | satty -f -
    return
    ;;
  esac
}

echo "${choice}"
main
