#!/usr/bin/env bash

selection=$(printf 'Area\nWindow\nScreen\nAll\nOCR\nSearch' | vicinae dmenu) || exit 1
scriptsDir=~/.config/hypr/scripts/

case $selection in
"Screen")
  sleep 0.5
  dms screenshot full --stdout | satty -f -
  return
  ;;
"Window")
  sleep 0.5
  dms screenshot window --stdout | satty -f -
  return
  ;;
"Area")
  sleep 0.5
  dms screenshot region --stdout | satty -f -
  return
  ;;
"All")
  sleep 0.5
  dms screenshot all --stdout | satty -f -
  return
  ;;
"OCR")
  sleep 0.5
  dms screenshot region --stdout | tesseract stdin stdout -l eng | wl-copy
  return
  ;;
"Search")
  sleep 0.5
  dms screenshot region
  xdg-open https://images.google.com
  return
  ;;
esac
