#!/bin/bash

BLUR_PASSES=$(hyprctl -j getoption decoration:blur_passes | jq ".int")

if [ "${BLUR_PASSES}" == "2" ]; then
  hyprctl keyword decoration:blur_size 3
  hyprctl keyword decoration:blur_passes 1
  notify-send "Normal"
else
  hyprctl keyword decoration:blur_size 7
  hyprctl keyword decoration:blur_passes 2
  notify-send "Glassy"
fi
