#!/bin/bash

ENABLED=$(hyprctl -j getoption decoration:blur:enabled | jq ".int")

if [ "${ENABLED}" == "1" ]; then
  hyprctl keyword decoration:blur:enabled false
  notify-send -i "$HOME/.config/hypr/mako/icons/hyprland.png" "Blur" "Normal"
else
  hyprctl keyword decoration:blur:enabled true
  notify-send -i "$HOME/.config/hypr/mako/icons/hyprland.png" "Blur" "Glassy"
fi
