#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='One Dark'
ICONS='Adwaita'
FONT='FuraSansCondensed Nerd Font 13'
# CURSOR='simp1e'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	# ${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
