#!/bin/bash

sleep 1
systemctl --user stop xdg-desktop-portal-hyprland
systemctl --user stop xdg-dessktop-portal
systemctl --user start xdg-desktop-portal-hyprland
sleep 2
systemctl --user start xdg-desktop-portal
