#!/usr/bin/env bash

ZJ_SESSIONS=$(zellij ls)
NO_SESSIONS=$(echo "${ZJ_SESSIONS}" | wc -l)

if [ "${NO_SESSIONS}" -ge 2 ]; then
    zellij attach \
    "$(echo "${ZJ_SESSIONS}" | awk '{print $1;}' | fzf --ansi)"
else
   zellij attach -c
fi
