#!/bin/sh

PATH=$HOME/bin/gamadv-xtd3:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.config/hypr/scripts/:$PATH
export PATH

cd ~ || exit

export HYPRLAND_LOG_WLR=1
export WLR_NO_HARDWARE_CURSORS=1
export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_THEME=Catppuccin-Mocha-Mauve-Cursor
export XCURSOR_SIZE=24
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORM="wayland;xcb"
export MOZ_DISABLE_RDD_SANDBOX=1
export NVD_BACKEND=direct
export LIBVA_DRIVER_NAME=nvidia
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __NV_PRIME_RENDER_OFFLOAD=1
export __VK_LAYER_NV_optimus=NVIDIA_only
export WLR_BACKEND=vulkan
export MOZ_ENABLE_WAYLAND=1
export GBM_BACKEND=nvidia-drm

exec Hyprland

# LIBVA_DRIVER_NAME=nvidia GBM_BACKEND=nvidia-drm __GLX_VENDOR_LIBRARY_NAME=nvidia __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only Hyprland
